application: logout
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name:  PIL
  version: 1.1.7

handlers:
- url: /javascript
  static_dir: javascript

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /.*
  script: main.app

